#pragma once
// Everything in one include. Individual headers can be included directly instead.
#include "algebra/natural.h"
#include "algebra/integer.h"
#include "algebra/rational.h"
#include "algebra/real.h"
#include "algebra/xrational.h"
#include "algebra/expr.h"
#include "algebra/vector.h"
#include "algebra/rational_vector.h"
#include "algebra/geometry.h"
#include "algebra/polygon2.h"
#include "algebra/polygon2_arc.h"
#include "algebra/polygon2_boolean.h"
#include "algebra/dual.h"
